### ISSUE TITLE
Refresh token

### ISSUE THREAD

**Issue by RookiePyl** [afterxleep/WireKit#4]
I am trying to add refresh token。
But I failed.
Any thoughts or suggestions are greatly appreciated.  ^_^

**Comment by afterxleep** [comment]
Hey, what do you mean?  Can you be a little more explicit about what you’re trying to achieve?

**Comment by RookiePyl** [comment]
when httpError == .unauthorized, The token is considered invalid.  

JHNetworkDispatcher.swift 

**`throw httpError(response. statusCode, data: data)`**

 How to refresh the token where an exception is thrown?

**Comment by afterxleep** [comment]
Hey.  

The library dioes not have a way to handle that, but you can check the
error and if you got it try to refresh the Token.

On August 24, 2023, Github Notifications ***@***.***>
wrote:
> when httpError == .unauthorized, The token is considered invalid.
>
> JHNetworkDispatcher.swift
>
> throw httpError(response. statusCode, data: data)
>
> How to refresh the token where an exception is thrown?
>

—
Reply to this email directly, view it on GitHub
<https://github.com/afterxleep/WireKit/issues/4#issuecomment-
1690924091>, or unsubscribe
<https://github.com/notifications/unsubscribe-
auth/AAI2MPNMH4BZX62ELOFOHMTXW3AVXANCNFSM6AAAAAA327WJ7M>.
You are receiving this because you commented.Message ID:
***@***.***>
